catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

packages: []

catalogs:
  backend:
    '@types/pg': ^8.16.0
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    iconv-lite: ^0.7.1
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/kit': ^4.2.2
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.10
    '@unocss/nuxt': ^66.5.10
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.2.2
    unocss: ^66.5.10
    unplugin: ^2.3.11
    vite: ^7.3.0
  dev:
    '@antfu/eslint-config': ^6.7.1
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
    typescript: ^5.9.3
    vue-tsc: ^3.1.8
  frontend:
    '@vueuse/core': ^14.1.0
    echarts: ^6.0.0
    nuxt-echarts: ^1.0.1
    pinia: ^3.0.4
    vue: ^3.5.25
    vue-echarts: ^8.0.1
  icons:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/twemoji': ^1.2.4
  utils:
    bignumber.js: ^9.3.1
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.43.0
    mitt: ^3.0.1
    paseto-ts: ^2.0.5
    zod: ^4.2.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
