packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.4
    drizzle-kit: ^0.31.2
    drizzle-orm: ^0.44.2
    pg: ^8.16.2
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@unocss/eslint-config': ^66.3.1
    '@unocss/nuxt': ^66.3.1
    '@vueuse/nuxt': ^13.4.0
    nuxt: ^3.17.5
    unocss: ^66.3.1
    unplugin: ^2.3.5
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.16.1
    eslint: ^9.29.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  frontend:
    '@vueuse/core': ^13.4.0
    echarts: ^5.6.0
    nuxt-echarts: ^0.3.3
    pinia: ^3.0.3
    vue: ^3.5.17
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/twemoji': ^1.2.2
  utils:
    bignumber.js: ^9.3.0
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.39.5
    mitt: ^3.0.1
    paseto-ts: ^2.0.5
    zod: ^3.25.67
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
