packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.5
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.5
    iconv-lite: ^0.7.0
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.1.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.0
    '@unocss/nuxt': ^66.5.0
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.0
    unocss: ^66.5.0
    unplugin: ^2.3.10
    vite: ^7.1.4
  dev:
    '@antfu/eslint-config': ^5.2.2
    eslint: ^9.34.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.9.2
    vue-tsc: ^3.0.6
  frontend:
    '@vueuse/core': ^13.9.0
    echarts: ^5.6.0
    nuxt-echarts: ^1.0.0
    pinia: ^3.0.3
    vue: ^3.5.21
    vue-echarts: ^7.0.3
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4
  utils:
    bignumber.js: ^9.3.1
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.39.10
    mitt: ^3.0.1
    paseto-ts: ^2.0.5
    zod: ^4.1.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
