catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade
packages: []

catalog:
  openai: ^6.16.0

catalogs:
  backend:
    '@nuxtjs/mcp-toolkit': ^0.6.2
    '@types/pg': ^8.16.0
    argon2: ^0.44.0
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    iconv-lite: ^0.7.2
    pg: ^8.17.2
  build:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint': ^1.12.1
    '@nuxt/kit': ^4.2.2
    '@nuxtjs/color-mode': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.6.0
    '@unocss/nuxt': ^66.6.0
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.2.2
    unocss: ^66.6.0
    unplugin: ^2.3.11
    vite: ^7.3.1
  dev:
    '@antfu/eslint-config': ^7.1.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    typescript: ^5.9.3
    vue-tsc: ^3.2.2
  frontend:
    '@vueuse/core': ^14.1.0
    echarts: ^6.0.0
    nuxt-echarts: ^1.0.1
    pinia: ^3.0.4
    vue: ^3.5.27
    vue-echarts: ^8.0.1
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/twemoji': ^1.2.5
  utils:
    bignumber.js: ^9.3.1
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.44.0
    mitt: ^3.0.1
    paseto-ts: ^2.0.5
    zod: ^4.3.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
