packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.5
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.44.6
    iconv-lite: ^0.7.0
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.1.3
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.3
    '@unocss/nuxt': ^66.5.3
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.3
    unocss: ^66.5.3
    unplugin: ^2.3.10
    vite: ^7.1.9
  dev:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.0.9
  frontend:
    '@vueuse/core': ^13.9.0
    echarts: ^6.0.0
    nuxt-echarts: ^1.0.1
    pinia: ^3.0.3
    vue: ^3.5.22
    vue-echarts: ^8.0.0
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/twemoji': ^1.2.4
  utils:
    bignumber.js: ^9.3.1
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.40.0
    mitt: ^3.0.1
    paseto-ts: ^2.0.5
    zod: ^4.1.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
