packages: []

catalogs:
  backend:
    '@types/pg': ^8.15.6
    drizzle-kit: ^0.31.6
    drizzle-orm: ^0.44.7
    iconv-lite: ^0.7.0
    pg: ^8.16.3
  build:
    '@nuxt/devtools': ^3.0.1
    '@nuxt/eslint': ^1.10.0
    '@nuxt/kit': ^4.2.1
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.3
    '@unocss/eslint-config': ^66.5.5
    '@unocss/nuxt': ^66.5.5
    '@vueuse/nuxt': ^14.0.0
    nuxt: ^4.2.1
    unocss: ^66.5.5
    unplugin: ^2.3.10
    vite: ^7.2.2
  dev:
    '@antfu/eslint-config': ^6.2.0
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.3
  frontend:
    '@vueuse/core': ^14.0.0
    echarts: ^6.0.0
    nuxt-echarts: ^1.0.1
    pinia: ^3.0.4
    vue: ^3.5.24
    vue-echarts: ^8.0.1
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/twemoji': ^1.2.4
  utils:
    bignumber.js: ^9.3.1
    dayjs-nuxt: ^2.1.11
    es-toolkit: ^1.41.0
    mitt: ^3.0.1
    paseto-ts: ^2.0.5
    zod: ^4.1.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
